apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-application
  template:
    metadata:
      labels:
        app: your-application
    spec:
      containers:
        - name: your-application
          image: your-application-image
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: mongodb
            - name: DATABASE_PORT
              value: "27017"
            - name: DATABASE_NAME
              value: your-database-name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
